# OPNFV FuncTest config (refer to schema/opnfv-functest.yang)
opnfv-functest:
  environment:
    installer:
      type: INSTALLER_TYPE
      address: INSTALLER_IP
    lab: NODE_NAME

# OpenStack config (native)
openstack:
  auth:
    endpoint: OS_AUTH_URL
    strategy: OS_AUTH_STRATEGY
    project:
      id: OS_PROJECT_ID
      name: OS_PROJECT_NAME
      domain-name: OS_PROJECT_DOMAIN_NAME
    username: OS_USERNAME
    password: OS_PASSWORD
    user-domain-name: OS_USER_DOMAIN_NAME
  test:
    image:  OS_TEST_IMAGE
    flavor: OS_TEST_FLAVOR
    network: OS_TEST_NETWORK
    
